# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- main
- develop
- feature/*

pool:
  vmImage: 'macos-latest'

jobs:

  - job: build_for_android_on_linux
    pool:
      vmImage: 'ubuntu-latest'
    steps:
      - task: Ant@1
        inputs:
          workingDirectory: ''
          buildFile: 'build.xml'
          javaHomeOption: 'JDKVersion'
          jdkVersionOption: '1.8'
          jdkArchitectureOption: 'x64'
          publishJUnitResults: true
          testResultsFiles: '**/TEST-*.xml'
          targets: 'configure-android compile-android install-android'
      - task: PublishBuildArtifacts@1
        inputs:
          pathtoPublish: 'artifactsOut'
          artifactName: 'ChickenHook'